name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"gftaimpact_demo-Training" \
            /o:"gftaimpact" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Build
        run: dotnet build

      - name: End Sonar Analysis
        run: |
          dotnet sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"